actions:
  1:
    action: delete_indices
    description: Delete indices older than 4 days (based on index name)
    options:
      ignore_empty_list: True
      disable_action: False
      continue_if_exception: True
      allow_ilm_indices: True
    filters:
    - filtertype: pattern
      kind: prefix
      value: k8s-production-
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 4
